server:
  port: 8085
  tomcat:
    max-http-form-post-size: 10485760
    max-swallow-size: 10485760

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/automata
    username: root
    password: Letmein
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: 'update'
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760

springdoc:
  swagger-ui:
    path: /docs

security:
  jwt:
    issuer: aycodes
    audience: aycodes
    secret-key: $2a$20$Jn08uDdO35bgvcnlBSrcmeAOIAeiUMnp00C6tJBjtdVJPTfBwkxAC
    #    2 hours validity
    token-validity: 7200
    clock-skew: 10

